/*
 * Project: Evo-Sim
 * Developed by: Irina Danes
 */

package electricVehicle;

public enum CarModel {
    AUDI_A3_E_TRON, BMW_I3, BMW_225XE, BMW_330E, BMW_530E, BMW_X5_40E, CITROEN_C_ZERO,
    JAGUAR_I_PACE, KIA_NIRO_PHEV, HYUNDAI_IONIQ_ELECTRIC, HYUNDAI_IONIQ_PLUGIN,
    MERCEDES_BENZ_C350E, MERCEDES_BENZ_E350E, MINI_COUNTRYMAN_COOPER_SE, MITSUBISHI_OUTLANDER_PHEV,
    NISSAN_E_NV200, NISSAN_LEAF, PORSCHE_PANAMERA_EHYBRID, RENAULT_ZOE, SMART_EQ_FORFOUR,
    SMART_EQ_FORTWO, TESLA_MODEL_X, TESLA_MODEL_S, TOYOTA_PRIUS_PLUGIN, VOLKSWAGEN_GOLF_GTE,
    VOLKSWAGEN_PASSAT_GTE, VOLVO_XC60_TWIN_ENGINE, VOLVO_XC90_TWIN_ENGINE, VOLVO_V90_TWIN_ENGINE,
    OTHER
}
