name: testing

on:
  push:
      branches: ["main", "develop"]
  pull_request:

jobs:
  testing:
    name: install and test package on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install pandoc on ubuntu
      if: startsWith(matrix.os, 'ubuntu')
      run: |
          sudo apt-get update
          sudo apt install -y pandoc

    - name: Install pandoc on macos
      if: startsWith(matrix.os, 'macos')
      run: brew install pandoc

    - name: Install pandoc on windows
      if: startsWith(matrix.os, 'windows')
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: install pandoc
    
    - name: Install Poetry
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
    
    - name: Install Application
      run: python -m poetry install
      
    - name: Test with pytest
      run: python -m poetry run pytest

    - name: Check doctests
      run: python -m poetry run sphinx-build -b doctest docs build

    - name: Build documentation
      run: python -m poetry run sphinx-build -b html docs build
